FROM node:lts-slim AS builder

WORKDIR /app

COPY . .

RUN npm ci && npm run build

FROM nginx:1.29-bookworm

LABEL service="personify-ui"

EXPOSE 80

COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
